export const alertConstants = {

    VIEW_ALL_USER_APP_NOTIFICATIONS_REQUEST: "VIEW_ALL_USER_APP_NOTIFICATIONS_REQUEST",
    VIEW_ALL_USER_APP_NOTIFICATIONS_SUCCESS: "VIEW_ALL_USER_APP_NOTIFICATIONS_SUCCESS",
    VIEW_ALL_USER_APP_NOTIFICATIONS_FAILURE: "VIEW_ALL_USER_APP_NOTIFICATIONS_FAILURE",

    VIEW_ACTIVE_USER_APP_NOTIFICATIONS_REQUEST: "VIEW_ACTIVE_USER_APP_NOTIFICATIONS_REQUEST",
    VIEW_ACTIVE_USER_APP_NOTIFICATIONS_SUCCESS: "VIEW_ACTIVE_USER_APP_NOTIFICATIONS_SUCCESS",
    VIEW_ACTIVE_USER_APP_NOTIFICATIONS_FAILURE: "VIEW_ACTIVE_USER_APP_NOTIFICATIONS_FAILURE",

};
