export const appConstants = {

    VIEW_ALL_APPS_REQUEST: "VIEW_ALL_APPS_REQUEST",
    VIEW_ALL_APPS_SUCCESS: "VIEW_ALL_APPS_SUCCESS",
    VIEW_ALL_APPS_FAILURE: "VIEW_ALL_APPS_FAILURE",

    VIEW_SINGLE_APP_REQUEST: "VIEW_SINGLE_APP_REQUEST",
    VIEW_SINGLE_APP_SUCCESS: "VIEW_SINGLE_APP_SUCCESS",
    VIEW_SINGLE_APP_FAILURE: "VIEW_SINGLE_APP_FAILURE",

    VIEW_APP_NAMES_REQUEST: "VIEW_APP_NAMES_REQUEST",
    VIEW_APP_NAMES_SUCCESS: "VIEW_APP_NAMES_SUCCESS",
    VIEW_APP_NAMES_FAILURE: "VIEW_APP_NAMES_FAILURE",

    SELECT_TRENDING_APPS_REQUEST: "SELECT_TRENDING_APPS_REQUEST",
    SELECT_TRENDING_APPS_SUCCESS: "SELECT_TRENDING_APPS_SUCCESS",
    SELECT_TRENDING_APPS_FAILURE: "SELECT_TRENDING_APPS_FAILURE",

    VIEW_APP_REVIEWS_REQUEST: "VIEW_APP_REVIEWS_REQUEST",
    VIEW_APP_REVIEWS_SUCCESS: "VIEW_APP_REVIEWS_SUCCESS",
    VIEW_APP_REVIEWS_FAILURE: "VIEW_APP_REVIEWS_FAILURE",

    GENERATE_SHIELDS_FOR_APPS_REQUEST: "GENERATE_SHIELDS_FOR_APPS_REQUEST",
    GENERATE_SHIELDS_FOR_APPS_SUCCESS: "GENERATE_SHIELDS_FOR_APPS_SUCCESS",
    GENERATE_SHIELDS_FOR_APPS_FAILURE: "GENERATE_SHIELDS_FOR_APPS_FAILURE",



    SEARCH_42_TEXT_REQUEST: "SEARCH_42_TEXT_REQUEST",
    SEARCH_42_TEXT_SUCCESS: "SEARCH_42_TEXT_SUCCESS",
    SEARCH_42_TEXT_FAILURE: "SEARCH_42_TEXT_FAILURE",

    SEARCH_42_IOS_ID_REQUEST: "SEARCH_42_IOS_ID_REQUEST",
    SEARCH_42_IOS_ID_SUCCESS: "SEARCH_42_IOS_ID_SUCCESS",
    SEARCH_42_IOS_ID_FAILURE: "SEARCH_42_IOS_ID_FAILURE",

    ADD_TEMP_LISTING_REQUEST: "ADD_TEMP_LISTING_REQUEST",
    ADD_TEMP_LISTING_SUCCESS: "ADD_TEMP_LISTING_SUCCESS",
    ADD_TEMP_LISTING_FAILURE: "ADD_TEMP_LISTING_FAILURE",

    VIEW_TEMP_SINGLE_APP_REQUEST: "VIEW_TEMP_SINGLE_APP_REQUEST",
    VIEW_TEMP_SINGLE_APP_SUCCESS: "VIEW_TEMP_SINGLE_APP_SUCCESS",
    VIEW_TEMP_SINGLE_APP_FAILURE: "VIEW_TEMP_SINGLE_APP_FAILURE",

};