export const categoryConstants = {

    VIEW_ALL_CATEGORIES_REQUEST: "VIEW_ALL_CATEGORIES_REQUEST",
    VIEW_ALL_CATEGORIES_SUCCESS: "VIEW_ALL_CATEGORIES_SUCCESS",
    VIEW_ALL_CATEGORIES_FAILURE: "VIEW_ALL_CATEGORIES_FAILURE",

    VIEW_SINGLE_CATEGORY_REQUEST: "VIEW_SINGLE_CATEGORY_REQUEST",
    VIEW_SINGLE_CATEGORY_SUCCESS: "VIEW_SINGLE_CATEGORY_SUCCESS",
    VIEW_SINGLE_CATEGORY_FAILURE: "VIEW_SINGLE_CATEGORY_FAILURE",


    VIEW_SINGLE_CATEGORY_INFO_REQUEST: "VIEW_SINGLE_CATEGORY_INFO_REQUEST",
    VIEW_SINGLE_CATEGORY_INFO_SUCCESS: "VIEW_SINGLE_CATEGORY_INFO_SUCCESS",
    VIEW_SINGLE_CATEGORY_INFO_FAILURE: "VIEW_SINGLE_CATEGORY_INFO_FAILURE"

}
