export const reviewConstants = {

    ADD_SHIELD_TO_APP_REQUEST: "ADD_SHIELD_TO_APP_REQUEST", 
    ADD_SHIELD_TO_APP_SUCCESS: "ADD_SHIELD_TO_APP_SUCCESS", 
    ADD_SHIELD_TO_APP_FAILURE: "ADD_SHIELD_TO_APP_FAILURE", 
    
    REVIEW_SUBMIT_REQUEST: "REVIEW_SUBMIT_REQUEST",
    REVIEW_SUBMIT_SUCCESS: "REVIEW_SUBMIT_SUCCESS",
    REVIEW_SUBMIT_FAILURE: "REVIEW_SUBMIT_FAILURE",

    RESET_ADDED_SHIELDS_REQUEST: "RESET_ADDED_SHIELDS_REQUEST",
    RESET_ADDED_SHIELDS_SUCCESS: "RESET_ADDED_SHIELDS_SUCCESS",
    RESET_ADDED_SHIELDS_FAILURE: "RESET_ADDED_SHIELDS_FAILURE"

};
