export const shieldConstants = {

    VIEW_ALL_SHIELDS_REQUEST: "VIEW_ALL_SHIELDS_REQUEST",
    VIEW_ALL_SHIELDS_SUCCESS: "VIEW_ALL_SHIELDS_SUCCESS",
    VIEW_ALL_SHIELDS_FAILURE: "VIEW_ALL_SHIELDS_FAILURE"

}
