export const VIEW_ALL_CATEGORIES = "VIEW_ALL_CATEGORIES";
export const VIEW_SINGLE_CATEGORY = "VIEW_SINGLE_CATEGORY";
export const VIEW_SINGLE_CATEGORY_INFO = "VIEW_SINGLE_CATEGORY_INFO";

export const VIEW_ALL_APPS = "VIEW_ALL_APPS";
export const VIEW_SINGLE_APP = "VIEW_SINGLE_APP";
export const VIEW_APP_NAMES = "VIEW_APP_NAMES";
export const SELECT_TRENDING_APPS = "SELECT_TRENDING_APPS";
export const GENERATE_SHIELDS_FOR_APPS = "GENERATE_SHIELDS_FOR_APPS";
export const VIEW_APP_REVIEWS = "VIEW_APP_REVIEWS";

export const VIEW_ALL_SHIELDS = "VIEW_ALL_SHIELDS";

export const ADD_SHIELD_TO_APP = "ADD_SHIELD_TO_APP";
export const RESET_ADDED_SHIELDS = "RESET_ADDED_SHIELDS";
export const REVIEW_SUBMIT = "REVIEW_SUBMIT";

// Functions to add based on initial state.json
export const NEW_USER = "NEW_USER";
export const NEW_GOOGLE_USER = "NEW_GOOGLE_USER"; 
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS ";

export const RENDER_TRENDING = "RENDER_TRENDING"; 

export const RENDER_ALL_APPS_DATA = "RENDER_ALL_APPS_DATA"; 
export const RENDER_SINGLE_APP_DATA = "RENDER_SINGLE_APP_DATA";

export const ADD_APP_TO_DATABASE = "ADD_APP_TO_DATABASE";

export const ADD_REVIEW_TO_APP = "ADD_REVIEW_TO_APP";

export const USER_INFO = 'USER_INFO'
export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT'

export const ALERT_CALLS = 'ALERT_CALLS'
