const officialCategoryData =
    [
        { 'label': '6000', 'name': 'Business', 'platform': 'ios', 'categoryId': null},
        { 'label': '6001', 'name': 'Weather', 'platform': 'ios'},
        { 'label': '6002', 'name': 'Utilities', 'platform': 'ios'},
        { 'label': '6003', 'name': 'Travel', 'platform': 'ios'},
        { 'label': '6004', 'name': 'Sports', 'platform': 'ios', 'categoryId': 4},
        { 'label': '6005', 'name': 'Social Networking', 'platform': 'ios'},
        { 'label': '6006', 'name': 'Reference', 'platform': 'ios'},
        { 'label': '6007', 'name': 'Productivity', 'platform': 'ios'},
        { 'label': '6008', 'name': 'Photo & Video', 'platform': 'ios', 'categoryId': 2},
        { 'label': '6009', 'name': 'News', 'platform': 'ios'},
        { 'label': '6010', 'name': 'Navigation', 'platform': 'ios'},
        { 'label': '6011', 'name': 'Music', 'platform': 'ios'},
        { 'label': '6012', 'name': 'Lifestyle', 'platform': 'ios'},
        { 'label': '6013', 'name': 'Health & Fitness', 'platform': 'ios'},
        { 'label': '6014', 'name': 'Games', 'platform': 'ios'},
        { 'label': '6015', 'name': 'Finance', 'platform': 'ios'},
        { 'label': '6016', 'name': 'Entertainment', 'platform': 'ios'},
        { 'label': '6017', 'name': 'Education', 'platform': 'ios'},
        { 'label': '6018', 'name': 'Book', 'platform': 'ios'},
        { 'label': '6020', 'name': 'Medical', 'platform': 'ios'},
        { 'label': '6021', 'name': 'Newsstand', 'platform': 'ios'},
        { 'label': '6022', 'name': 'Catalogs', 'platform': 'ios'},
        { 'label': '6023', 'name': 'Food & Drink', 'platform': 'ios'},
        { 'label': '6024', 'name': 'Shopping', 'platform': 'ios'},
        { 'label': '6025', 'name': 'Stickers', 'platform': 'ios'},
        { 'label': 'GAME', 'name': 'All games', 'platform': 'android'},
        { 'label': 'ART_AND_DESIGN', 'name': 'Art & Design', 'platform': 'android'},
        { 'label': 'AUTO_AND_VEHICLES', 'name': 'Auto & Vehicles', 'platform': 'android'},
        { 'label': 'BEAUTY', 'name': 'Beauty', 'platform': 'android'},
        { 'label': 'BOOKS_AND_REFERENCE', 'name': 'Books & Reference', 'platform': 'android'},
        { 'label': 'BUSINESS', 'name': 'Business', 'platform': 'android'},
        { 'label': 'COMICS', 'name': 'Comics', 'platform': 'android'},
        { 'label': 'COMMUNICATION', 'name': 'Communication', 'platform': 'android'},
        { 'label': 'DATING', 'name': 'Dating', 'platform': 'android'},
        { 'label': 'EDUCATION', 'name': 'Education', 'platform': 'android'},
        { 'label': 'ENTERTAINMENT', 'name': 'Entertainment', 'platform': 'android'},
        { 'label': 'EVENTS', 'name': 'Events', 'platform': 'android'},
        { 'label': 'FINANCE', 'name': 'Finance', 'platform': 'android'},
        { 'label': 'FOOD_AND_DRINK', 'name': 'Food & Drink', 'platform': 'android'},
        { 'label': 'HEALTH_AND_FITNESS', 'name': 'Health & Fitness', 'platform': 'android'},
        { 'label': 'HOUSE_AND_HOME', 'name': 'House & Home', 'platform': 'android'},
        { 'label': 'LIFESTYLE', 'name': 'Lifestyle', 'platform': 'android'},
        { 'label': 'MAPS_AND_NAVIGATION', 'name': 'Maps & Navigation', 'platform': 'android'},
        { 'label': 'MEDICAL', 'name': 'Medical', 'platform': 'android'},
        { 'label': 'MUSIC_AND_AUDIO', 'name': 'Music & Audio', 'platform': 'android'},
        { 'label': 'NEWS_AND_MAGAZINES', 'name': 'News & Magazines', 'platform': 'android'},
        { 'label': 'PARENTING', 'name': 'Parenting', 'platform': 'android'},
        { 'label': 'PERSONALIZATION', 'name': 'Personalization', 'platform': 'android'},
        { 'label': 'PHOTOGRAPHY', 'name': 'Photography', 'platform': 'android'},
        { 'label': 'PRODUCTIVITY', 'name': 'Productivity', 'platform': 'android'},
        { 'label': 'SHOPPING', 'name': 'Shopping', 'platform': 'android'},
        { 'label': 'SOCIAL', 'name': 'Social', 'platform': 'android'},
        { 'label': 'SPORTS', 'name': 'Sports', 'platform': 'android'},
        { 'label': 'TOOLS', 'name': 'Tools', 'platform': 'android'},
        { 'label': 'TRAVEL_AND_LOCAL', 'name': 'Travel & Local', 'platform': 'android'},
        { 'label': 'VIDEO_PLAYERS', 'name': 'Video Players & Editors', 'platform': 'android'},
        { 'label': 'WEATHER', 'name': 'Weather', 'platform': 'android'},
        { 'label': 'LIBRARIES_AND_DEMO', 'name': 'Libraries & Demo', 'platform': 'android'},
        { 'label': 'ANDROID_WEAR', 'name': 'Android Wear', 'platform': 'android'}
    ];

module.exports = officialCategoryData;